version: 2

build:
  os: ubuntu-22.04
  tools:
    python: '3.12'
  commands:
    - python -m pip install --upgrade pip
    - pip install hatch
    - hatch run docs:build
    - mkdir -p $READTHEDOCS_OUTPUT/html/
    - cp -r docs/_build/* $READTHEDOCS_OUTPUT/html/

sphinx:
  builder: html
  configuration: docs/conf.py
