name: Code

on:
  workflow_call:
  push:
    branches-ignore:
      - main
      - 'releases/**'
    tags-ignore:
      - '**'
    paths:
      - 'src/**'
      - 'tests/**'
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analysis:
    name: Static analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Hatch
        run: |
          python -m pip install --upgrade pip
          pip install hatch
      - name: Check typing
        run: hatch run tools:type-check
      - name: Check linting
        run: hatch run tools:lint
      - name: Check format
        run: hatch run tools:format --check
  tests:
    name: Python ${{ matrix.python-version }} tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Hatch
        run: |
          python -m pip install --upgrade pip
          pip install hatch
      - name: Run tests with coverage
        run: hatch run cov-tests
      - name: Upload coverage data
        uses: actions/upload-artifact@v4
        with:
          name: coverage-data-${{ matrix.python-version }}
          path: .coverage.*
  coverage:
    name: Coverage report
    runs-on: ubuntu-latest
    needs: tests
    if: always()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Hatch
        run: |
          python -m pip install --upgrade pip
          pip install hatch
      - name: Download coverage data
        uses: actions/download-artifact@v4
        with:
          pattern: coverage-data-*
          merge-multiple: true
      - name: Generate coverage report
        run: hatch run cov-report
      - name: Upload the HTML report
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: htmlcov
        if: ${{ failure() }}
